# Generated by Django 4.2.17 on 2025-01-14 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0002_remove_subject_model_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_model',
            name='period',
        ),
        migrations.RemoveField(
            model_name='subject_model',
            name='staff',
        ),
        migrations.AddField(
            model_name='subject_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-14'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='allocation_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Staff_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.staff_model')),
                ('Subject_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.subject_model')),
            ],
        ),
    ]
