# Generated by Django 4.2.17 on 2025-01-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0003_remove_subject_model_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_model',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
