# Generated by Django 4.2.17 on 2025-01-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0004_alter_subject_model_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_model',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
