# Generated by Django 4.2.17 on 2025-01-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0005_leave_model_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_model',
            old_name='status',
            new_name='leavestatus',
        ),
    ]
